from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


class AgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="List of messages to be processed by the agent.")
    user_question : str = Field(..., description = "The original question asked by the user.")
    curated_ques : str = Field(..., description = "Curated user question")
    prompt_query_context : str = Field(..., description = "A detailed prompt with SQL DB Context that will help agent to generate SQL query for the user question.")
    generated_sql_query : str = Field(..., description = "The SQL query generated by the agent based on the user question and context.")
    is_safe : Literal["Yes", "No"] = Field(..., description = "Indicates whether the generated SQL query is safe to execute.")
    #answer : str = Field(..., description = "The answer provided by the agent after executing the SQL query.")
    comments : str = Field(..., description = "Comments or feedback provided by the agent regarding the safety of the SQL query.")
    sql_query_execution_result : str = Field(..., description = "The result of executing the generated SQL query.")
    final_answer : str = Field(..., description = "The final answer provided by the agent after processing the user question and SQL query results.")

class JudgeSchema(BaseModel):
    answer : Literal["Yes", "No"] = Field(..., description = "Indicates whether the generated SQL query is safe to execute or not.")
    comments : str = Field(..., description = "Comments or feedback provided by the judge regarding the safety of the SQL query.")

class ETLAgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="List of messages to be processed by the agent.")

class RouterSchema(BaseModel):
    answer: Literal["sql","etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")


class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")

